### ISSUE TITLE
Can't import specifications on Windows

### ISSUE THREAD

**Issue by sodre** [khornberg/octokitpy-routes#83]
Hi,

First thank you for setting this package up. I am working on a framework inspired by Probot to create GitHub Apps using python, in the process of running my [distributed unit tests][detox] I ran into the following exception while using importing `webhooks` from `octokitpy`

```python-traceback
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\zeroae\goblet\chalice\__init__.py", line 2, in <module>
    from .blueprint import bp
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\zeroae\goblet\chalice\blueprint.py", line 20, in <module>
    from octokit import webhook
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\octokit\__init__.py", line 8, in <module>
    from octokit_routes import specifications
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\octokit_routes\__init__.py", line 13, in <module>
    specifications = {spec.replace('.json', ''): _load_spec(spec) for spec in specs}
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\octokit_routes\__init__.py", line 13, in <dictcomp>
    specifications = {spec.replace('.json', ''): _load_spec(spec) for spec in specs}
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\octokit_routes\__init__.py", line 9, in _load_spec
    return json.load(f)
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5259063: character maps to <undefined>
============================== warnings summary ===============================
```

[detox]: https://github.com/zeroae/zeroae-goblet/pull/5/checks?check_run_id=548420142

**Comment by khornberg** [comment]
I’ve not used windows and python before. What do you think is the issue that causes the exception?

**Comment by sodre** [comment]
We could do a matrixed build of this package and see if the error shows up there too. Let me know if you want to try it out.

**Comment by sodre** [comment]
[According to StackOverflow][overflow], the file encoding could not be detected on the windows side. One possible solution is to pass the encoding="utf-8" when opening the spec file.

[overflow]: https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character

**Comment by khornberg** [comment]
If you want to try that out, go for it
